### ISSUE TITLE
Ingest VSX catalog

### ISSUE THREAD

**Issue by janvanroestel** [dmitryduev/kowalski#106]
The VSX catalog contains 2M variable sources. For automatic filtering and crossmatching, this catalogue is useful to have.

**Feature Summary**
Ingest VSX catalogue from vizier: http://vizier.u-strasbg.fr/viz-bin/VizieR?-source=B%2Fvsx The vizier catalog is regularly updated, and we like to keep to Kowalski version up to date too (can be done manually).

**Implementation details**
requires a python script that takes the downloaded Vizier catalog and ingests it into Kowalski. Similar to other catalogs.

**Comment by dmitryduev** [comment]
@janvanroestel any progress on this?

**Comment by dmitryduev** [comment]
Closing as stalled. Feel free to reopen in the future.
