### ISSUE TITLE
Add VLASS as a database option

### ISSUE THREAD

**Issue by mcoughlin** [dmitryduev/kowalski#89]
VLASS is a useful point source catalog of radio sources:

https://cirada.ca/vlasscatalogueql0

Can be loaded as, for example:

        df = pd.read_csv(catalog_file)
        df = df[df["Duplicate_flag"] < 2]
        df = df[df["Quality_flag"] == 0]
        df = df[df["Total_flux"] >= 1]
        df = df[df["Total_flux"]/df["E_Total_flux"] >= 5]

**Comment by dmitryduev** [comment]
See https://github.com/dmitryduev/kowalski/blob/master/tools/ingest_ztf_source_features.py for reference.

**Comment by mcoughlin** [comment]
This and the test_ingester.py script looks like good examples. Do you also have an example somewhere of the script you used for some other catalog?

**Comment by dmitryduev** [comment]
See here: https://github.com/dmitryduev/kowalski/tree/master/tools
There are scripts for Gaia and PS1 STRM.
