### ISSUE TITLE
add IGAPS dataset

### ISSUE THREAD

**Issue by janvanroestel** [dmitryduev/kowalski#97]
IPHAS dr2 has been superseded by the IGAPS catalog and the survey should be updated

Feature Summary
The IPHAS dr2 catalog has been superseded by IGAPS (http://www.star.ucl.ac.uk/IGAPS/survey.shtml). IGAPS included both IPHAS and UVEX; and contains data in the Ugriz-filters. Especially the U-band data is important for compact object science.

Usage / behavior
This is simply an update of a catalog available for crossmatching

Implementation details
This is simply an update of a catalog. If needed, some catalog columns can be omitted.

Additional context
IGAPS is a Galactic Plane catalog, having this available soon would be nice since the Galactic plane is rising again in the sky

**Comment by mcoughlin** [comment]
@dmitryduev This fix went in, did it get ingested and we can close?

**Comment by dmitryduev** [comment]
@mcoughlin started ingesting and noticed the following:
![image](https://user-images.githubusercontent.com/7557205/115842009-41f58080-a3d2-11eb-9cde-f99c5c1ccd14.png)

missed this when reviewing, sorry about that...

Would you mind fixing the following:
- Properly parse all the id/name strings
- Ditch all NaNs before ingesting - it's NoSQL, it's ok not to have all the fields for each document.

Thanks!

**Comment by dmitryduev** [comment]
@mcoughlin @janvanroestel finished ingesting. Can IPHAS be ditched now?

**Comment by janvanroestel** [comment]
yes, IPHAS can be dropped.
